# Generated by Django 5.2 on 2025-05-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Движение средств', 'verbose_name_plural': 'Движения средств'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='statusflow',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='typeflow',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='cashflow.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата движения'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='cashflow.statusflow', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='cashflow.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='typeflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='cashflow.typeflow', verbose_name='Тип движения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='typeflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='cashflow.typeflow', verbose_name='Тип движения'),
        ),
        migrations.AlterField(
            model_name='statusflow',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='supercategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='cashflow.category', verbose_name='Надкатегория'),
        ),
        migrations.AlterField(
            model_name='typeflow',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
