# Generated by Django 5.2 on 2025-05-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_alter_cashflow_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='created_at',
            field=models.DateField(verbose_name='Дата движения'),
        ),
    ]
