# Generated by Django 5.2 on 2025-05-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_alter_cashflow_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['-created_at', 'amount'], 'verbose_name': 'Движение средств', 'verbose_name_plural': 'Движения средств'},
        ),
    ]
