# Generated by Django 5.2 on 2025-05-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_alter_cashflow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['-created_at', '-amount'], 'verbose_name': 'Движение средств', 'verbose_name_plural': 'Движения средств'},
        ),
    ]
